ALTER TABLE usuarios
ADD COLUMN logradouro VARCHAR(255),
ADD COLUMN bairro VARCHAR(100),
ADD COLUMN cep VARCHAR(8),
ADD COLUMN cidade VARCHAR(100),
ADD COLUMN uf VARCHAR(2),
ADD COLUMN numero VARCHAR(20),
ADD COLUMN complemento VARCHAR(100);